# Generated by Django 4.1.7 on 2023-04-07 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='fechahora',
            new_name='fecha_hora',
        ),
        migrations.RenameField(
            model_name='chat',
            old_name='id_message',
            new_name='id_mensaje',
        ),
    ]
